### ISSUE TITLE
Zipped binaries in SCM

### ISSUE THREAD

**Issue by Mailaender** [SSLcom/ci-images#1]
Can you please create https://github.com/SSLcom/CodeSigner tag the versions and put the compiled .zip as a release attachment? Overwriting https://www.ssl.com/download/codesigntool-for-linux-and-macos/ with a new .zip in a different folder structure like you recently did is also unacceptable as each new version breaks the CI run.

**Comment by bayrakmustafa** [comment]
@Mailaender What is the difference in the folder structure? Can you give an example? What problem are you having?

We have added zip binaries of the latest versions to https://github.com/SSLcom/CodeSignTool/releases. You can use it in CI/CD processes.

**Comment by Mailaender** [comment]
Both https://github.com/SSLcom/ci-images/blob/main/CodeSignTool-v1.2.5.zip and https://github.com/SSLcom/ci-images/blob/main/CodeSignTool-v1.2.7.zip are included in SCM. You should download them in https://github.com/SSLcom/ci-images/blob/main/Dockerfile instead.

**Comment by Mailaender** [comment]
> What is the difference in the folder structure? Can you give an example? What problem are you having?

https://www.ssl.com/download/codesigntool-for-linux-and-macos/ was a flat zip. Then you changed the directory structure to contain `CodeSignTool-v1.2.7` as the topmost folder. As the download URL is unversioned, this change came out of nowhere and caused disruptions. https://github.com/SSLcom/CodeSignTool/releases is a great relief. Thanks!

**Comment by bayrakmustafa** [comment]
> Both https://github.com/SSLcom/ci-images/blob/main/CodeSignTool-v1.2.5.zip and https://github.com/SSLcom/ci-images/blob/main/CodeSignTool-v1.2.7.zip are included in SCM. You should download them in https://github.com/SSLcom/ci-images/blob/main/Dockerfile instead.

I made the necessary update for v1.2.7. https://github.com/sslcom/codesigntool/releleses/tag/v1.2.7 with the zip file at Docker image's latest and 1.2.7 versions. I will pay attention to this in the next release. Thanks @Mailaender

**Comment by Mailaender** [comment]
Thanks.
