### ISSUE TITLE
Potential authentication bug affecting codesigner-win Docker image

### ISSUE THREAD

**Issue by beninada** [SSLcom/ci-images#5]
I cannot seem to authenticate against the Windows codesigner Docker image, and I was wondering if I could request your help. It seems like I _may_ be running into a bug with the codesigner-win image.

When I run `docker run -i --rm --env-file .env ghcr.io/sslcom/codesigner-win:latest get_credential_ids` to fetch my credential IDs, I receive this error:
> Error: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.

Interestingly, I can run the same command with the same .env file on my Mac using the Linux image, and it successfully authenticates and returns my credential IDs. This seems to indicate that the credentials I am passing in via the .env file are correct. Even more interestingly, if I use the [demo credentials](https://github.com/SSLcom/ci-images/blob/main/.env) instead of my own credentials, the command succeeds on both Windows and Mac (using the codesigner-win and codesigner images, respectively). 

Btw, I receive the same authorization error when I attempt to use the other commands e.g. sign.

My .env file is in the format:
```
USERNAME="redacted"
PASSWORD="redacted"
TOTP_SECRET="redacted"
CREDENTIAL_ID="redacted"
ENVIRONMENT_NAME="PROD"
```

Thanks in advance for your help.

**Comment by bayrakmustafa** [comment]
@beninada Can you pull the latest version again and test it? There is a bug in the entrypoint.ps1 file. It should be resolved by now. The environment in which the signing works will be written to the output as `Running ESigner.com CodeSign Action on Production`.

**Comment by beninada** [comment]
Thanks @bayrakmustafa, the authorization grant issue is resolved with the latest version.

Unfortunately, I'm encountering a new issue. When I attempt to sign with a TOTP, I receive "Error: The OTP is invalid." This seems like it might be related to https://github.com/SSLcom/esigner-codesign/issues/17. I tried the resolution described in that issue, but I am still getting an error. Any advice? Thanks again.

**Comment by beninada** [comment]
I was able to resolve the invalid OTP error by setting my machine's time server to time.nist.gov.
