### ISSUE TITLE
Unmatched arguments error when signing with a space in file name

### ISSUE THREAD

**Issue by beninada** [SSLcom/ci-images#6]
I am attempting to sign a file with spaces in its name e.g. `test 123.exe` with the `codesigner-win2019` image. I get an error: Unmatched arguments at index 2: '123.exe'. Is there some way to escape the space?

I think the issue is probably related to https://github.com/SSLcom/esigner-codesign/issues/11.

**Comment by beninada** [comment]
A related quirk - some files we need to sign have parentheses in their file names e.g. `test-(123).exe` resulting in this error:
```
123 : The term '123' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:93
+ ... -input_file_path=C:\CodeSignTool\output\test-(123)-window ...
+                                                            ~~~~~~
    + CategoryInfo          : ObjectNotFound: (123:String) [], CommandNotFo 
   undException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Codesigner thinks I am trying to interpolate the string with a cmdlet, 
function, script file, or operable program. Having the ability to escape or ignore parentheses would resolve this issue.

**Comment by bayrakmustafa** [comment]
@beninada I made an update about the problem. You can check the example below. You can avoid special character problems with `` characters.

```bash
docker run -i --rm --volume .\artifacts:C:\CodeSignTool\output --env-file .env codesigner-win2019 sign ``-input_file_path="C:\CodeSignTool\examples\codesign`` ``(1``).ps1" ``-output_dir_path=C:\CodeSignTool\output
``` 

Ref: https://github.com/SSLcom/ci-images/blob/main/.github/workflows/docker.yml#L219

**Comment by beninada** [comment]
Thanks @bayrakmustafa. I was able to find a workaround that eliminates spaces from the file name, but I appreciate your work on this!
